# Generated by Django 4.2.4 on 2023-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('overview', models.TextField(blank=True, max_length=255, null=True, verbose_name='Cодержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('view_counter', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
