# Generated by Django 4.2.4 on 2023-08-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='overview',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
