# Generated by Django 4.2.4 on 2023-08-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(default=None, verbose_name='Дата последнего изменения'),
        ),
    ]
