# Generated by Django 4.2.4 on 2023-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
