# Generated by Django 4.2.4 on 2023-09-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_version_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
